# Costruzione dello script per ottenere i dati

In [2]:
import urllib3
import requests
import pandas as pd
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
import requests
import time
from io import StringIO
from io import BytesIO

### Dati incidenti

In [3]:
# script V2 per incidenti
current_year = time.localtime().tm_year
dfs_incidenti =[]
headers = {'Accept': 'application/vnd.sdmx.data+csv;version=1.0.0'}


for i in range(2001,current_year): #metto current_year nel range perché il range lo esclude
    url =   "https://esploradati.istat.it/SDMXWS/rest/data/41_983?startPeriod=" + str(i) + "&endPeriod="+ str(i-1)
    response_incidenti = requests.get(url, headers=headers, verify=False)

    df = pd.read_csv(StringIO(response_incidenti.text))

    dfs_incidenti.append(df)

    time.sleep(15)

df_incidenti_raw = pd.concat(dfs_incidenti, ignore_index=True)

KeyboardInterrupt:

In [27]:
df_incidenti_raw

,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT,NoRecordsFound
0,IT1:41_983(1.0),A,1001.0,KILLINJ,F,2001.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IT1:41_983(1.0),A,1001.0,KILLINJ,M,2001.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IT1:41_983(1.0),A,1001.0,ROADACC,9,2001.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IT1:41_983(1.0),A,1002.0,KILLINJ,F,2001.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IT1:41_983(1.0),A,1002.0,KILLINJ,M,2001.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573547,IT1:41_983(1.0),A,111106.0,KILLINJ,M,2024.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573548,IT1:41_983(1.0),A,111106.0,ROADACC,9,2024.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573549,IT1:41_983(1.0),A,111107.0,KILLINJ,F,2024.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573550,IT1:41_983(1.0),A,111107.0,KILLINJ,M,2024.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
573551,IT1:41_983(1.0),A,111107.0,ROADACC,9,2024.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_incidenti_raw = df_incidenti_raw[['DATAFLOW','FREQ', 'REF_AREA', 'DATA_TYPE', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE']]

In [29]:
df_incidenti_raw[["REF_AREA","TIME_PERIOD"]] = df_incidenti_raw[["REF_AREA","TIME_PERIOD"]].astype(int)

In [30]:
df_incidenti_raw_pivot = df_incidenti_raw.pivot(index=['DATAFLOW', 'FREQ', 'REF_AREA', 'TIME_PERIOD'],columns='RESULT', values='OBS_VALUE').reset_index()

In [45]:
df_incidenti_raw_pivot
df_incidenti_raw_pivot.groupby('TIME_PERIOD', as_index=False)['REF_AREA'].count()

    TIME_PERIOD  REF_AREA
0          2001      8101
1          2002      8102
2          2003      8102
3          2004      8100
4          2005      8101
5          2006      8101
6          2007      8101
7          2008      8101
8          2009      8100
9          2010      8094
10         2011      8092
11         2012      8092
12         2013      8092
13         2014      8059
14         2015      8047
15         2016      8000
16         2017      7978
17         2018      7954
18         2019      7915
19         2020      7904
20         2021      7904
21         2022      7904
22         2023      7901
23         2024      6339

### Dati comuni: nome, superficie, popolazione

Inizialmente ho considerato risorse da scaricare per popolazione<br>
source dati 2001-2018: https://demo.istat.it/app/?i=RBD&l=it <br>
souce dati 2019-2025: https://demo.istat.it/app/?l=it&a=2025&i=P02

Ho poi realizzato che potevo scaricare dal'API SITUAS i dati per ogni anno ciclando.

In [32]:
current_year = time.localtime().tm_year
dfs = []

for i in range(2001, current_year, 1):
    url = 'https://situas-servizi.istat.it/publish/reportspooljson?pfun=74&pdata=31/12/'+ str(i)
    r= requests.get(url, verify=False)

    df = pd.DataFrame.from_dict(r.json()['resultset'])

    dfs.append(df)

df_comuni_raw = pd.concat(dfs, ignore_index=True)

In [36]:
df_comuni_raw = df_comuni_raw[['PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES', 'ANNO_AREA', 'COD_RIP', 'COD_REG', 'COD_UTS']]

In [37]:
df_comuni_raw["ANNO_AREA"] = df_comuni_raw["ANNO_AREA"].astype(int)

In [47]:
df_comuni_raw.groupby('ANNO_AREA', as_index=False)['PRO_COM'].count()

    ANNO_AREA  PRO_COM
0        2001     8102
1        2002     8102
2        2003     8100
3        2004     8101
4        2005     8101
5        2006     8101
6        2007     8101
7        2008     8101
8        2009     8100
9        2010     8094
10       2011     8092
11       2012     8092
12       2013     8090
13       2014     8057
14       2015     8046
15       2016     7998
16       2017     7978
17       2018     7954
18       2019     7914
19       2020     7903
20       2021     7904
21       2022     7904
22       2023     7900
23       2024     7896
24       2025     7896

### Unire i datasets: incidenti + comuni

In [38]:
#new_df = df_ricevente.merge(df_daAttaccarci[['col1','col2']], how='lef', left_on='coldeldatasetricevente', right_on='col del nuovo dataset da matcharci')
df_raw = df_incidenti_raw_pivot.merge(df_comuni_raw, how='left', left_on=['REF_AREA', 'TIME_PERIOD'], right_on=['PRO_COM', 'ANNO_AREA'])

In [39]:
df_raw = df_raw[['COMUNE','REF_AREA','AREA_KMQ','POP_RES', '9', 'F', 'M','TIME_PERIOD']]
df_raw = df_raw.rename(columns={"COMUNE": "Nome Comune","REF_AREA": "Codice Comune", "AREA_KMQ": "Area(kmq)", "POP_RES": "Popolazione", "9": "Incidenti", "F": "Feriti", "M": "Morti", "TIME_PERIOD": "Anno" })

In [40]:
df_raw[['Popolazione','Incidenti', 'Feriti', 'Morti']] = df_raw[['Popolazione','Incidenti', 'Feriti', 'Morti']].round()
df_raw[['Popolazione','Incidenti', 'Feriti', 'Morti']] = df_raw[['Popolazione','Incidenti', 'Feriti', 'Morti']].astype("Int64")

In [43]:
df_raw[df_raw['Codice Comune'] == 1001]

,Nome Comune,Codice Comune,Area(kmq),Popolazione,Incidenti,Feriti,Morti,Anno
0,Agliè,1001,13.1462,2557,5,10,0,2001
1,Agliè,1001,13.1462,2538,5,10,0,2002
2,Agliè,1001,13.1462,2588,4,7,0,2003
3,Agliè,1001,13.1462,2679,9,13,0,2004
4,Agliè,1001,13.1462,2674,2,2,0,2005
5,Agliè,1001,13.1462,2662,1,1,0,2006
6,Agliè,1001,13.1462,2658,8,12,0,2007
7,Agliè,1001,13.1462,2638,5,10,0,2008
8,Agliè,1001,13.1462,2622,4,7,0,2009
9,Agliè,1001,13.1462,2615,7,14,0,2010
10,Agliè,1001,13.1462,2657,4,6,0,2011
11,Agliè,1001,13.1462,2722,3,8,0,2012
12,Agliè,1001,13.1462,2748,4,5,0,2013
13,Agliè,1001,13.1462,2701,6,11,0,2014
14,Agliè,1001,13.1462,2644,5,9,0,2015
15,Agliè,1001,13.1462,2661,5,8,0,2016
16,Agliè,1001,13.1462,2658,0,0,0,2017
17,Agliè,1001,13.1462,2634,1,1,0,2018
18,Agliè,1001,13.1462,2621,3,5,0,2019
19,Agliè,1001,13.1462,2545,4,4,0,2020
20,Agliè,1001,13.1463,2562,2,2,0,2021
21,Agliè,1001,13.1463,2568,3,5,0,2022
22,Agliè,1001,13.1463,2596,3,6,1,2023
23,Agliè,1001,13.1463,2585,2,5,0,2024

In [ ]:
df_raw = df_raw[df_raw['Nome Comune'].notna()].reset_index(drop=True)

In [101]:
df_raw.to_csv('../data/incidenti_comuni.csv', index=False)

### Source per dati terrioriali: area geografica, regione

In [3]:
url_codici_unita_amministrative = 'https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xlsx'
response_codici_unita_amministrative = requests.get(url_codici_unita_amministrative, verify=False)
df_codici_unita_amministrative = pd.read_excel(BytesIO(response_codici_unita_amministrative.content))

In [4]:
df_codici_unita_amministrative

,Codice Regione,Codice dell'Unità territoriale sovracomunale \n(valida a fini statistici),Codice Provincia (Storico)(1),Progressivo del Comune (2),Codice Comune formato alfanumerico,Denominazione (Italiana e straniera),Denominazione in italiano,Denominazione altra lingua,Codice Ripartizione Geografica,Ripartizione geografica,...,Codice Comune numerico con 110 Province (dal 2010 al 2016),Codice Comune numerico con 107 Province (dal 2006 al 2009),Codice Comune numerico con 103 Province (dal 1995 al 2005),Codice Catastale del Comune,Codice NUTS1 2021,Codice NUTS2 2021 (3),Codice NUTS3 2021,Codice NUTS1 2024,Codice NUTS2 2024 (3),Codice NUTS3 2024
0,1,201,1,1,1001,Agliè,Agliè,NaN,1,Nord-ovest,...,1001,1001,1001,A074,ITC,ITC1,ITC11,ITC,ITC1,ITC11
1,1,201,1,2,1002,Airasca,Airasca,NaN,1,Nord-ovest,...,1002,1002,1002,A109,ITC,ITC1,ITC11,ITC,ITC1,ITC11
2,1,201,1,3,1003,Ala di Stura,Ala di Stura,NaN,1,Nord-ovest,...,1003,1003,1003,A117,ITC,ITC1,ITC11,ITC,ITC1,ITC11
3,1,201,1,4,1004,Albiano d'Ivrea,Albiano d'Ivrea,NaN,1,Nord-ovest,...,1004,1004,1004,A157,ITC,ITC1,ITC11,ITC,ITC1,ITC11
4,1,201,1,6,1006,Almese,Almese,NaN,1,Nord-ovest,...,1006,1006,1006,A218,ITC,ITC1,ITC11,ITC,ITC1,ITC11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7889,20,119,119,20,119020,Sant'Antioco,Sant'Antioco,NaN,5,Isole,...,107020,107020,92063,I294,ITG,ITG2,ITG2H,ITG,ITG2,ITG2H
7890,20,119,119,21,119021,Tratalias,Tratalias,NaN,5,Isole,...,107021,107021,92085,L337,ITG,ITG2,ITG2H,ITG,ITG2,ITG2H
7891,20,119,119,22,119022,Villamassargia,Villamassargia,NaN,5,Isole,...,107022,107022,92094,L968,ITG,ITG2,ITG2H,ITG,ITG2,ITG2H
7892,20,119,119,23,119023,Villaperuccio,Villaperuccio,NaN,5,Isole,...,107023,107023,92104,M278,ITG,ITG2,ITG2H,ITG,ITG2,ITG2H
7893,20,119,119,24,119024,Teulada,Teulada,NaN,5,Isole,...,92084,92084,92084,L154,ITG,ITG2,ITG2H,ITG,ITG2,ITG2H

In [ ]:
#new_df = df_ricevente.merge(df_daAttaccarci[['col1','col2']], how='lef', left_on='coldeldatasetricevente', right_on='col del nuovo dataset da matcharci')
#df_completo = df_raw.merge(df_codici_unita_amministrative[['Codice Regione', 'Denominazione Regione']], how='left', left_on='COD_REG', right_on='Codice Regione')

In [37]:
df_raw

,Nome Comune,Codice Comune,Area(kmq),Popolazione,Incidenti,Feriti,Morti,Anno
0,Agliè,1001,13.1462,2557,5,10,0,2001
1,Agliè,1001,13.1462,2538,5,10,0,2002
2,Agliè,1001,13.1462,2588,4,7,0,2003
3,Agliè,1001,13.1462,2679,9,13,0,2004
4,Agliè,1001,13.1462,2674,2,2,0,2005
...,...,...,...,...,...,...,...,...
197518,Villaspeciosa,111107,27.1943,2536,5,7,0,2021
197519,Villaspeciosa,111107,27.1943,2575,1,1,0,2022
197520,Villaspeciosa,111107,27.1943,2616,4,5,0,2023
197521,Villaspeciosa,111107,27.1943,2628,3,5,0,2024
197522,Villaspeciosa,111107,27.1943,2628,3,5,0,2024

In [5]:
#new_df = df_ricevente.merge(df_daAttaccarci[['col1','col2']], how='lef', left_on='coldeldatasetricevente', right_on='col del nuovo dataset da matcharci')
unione_test = df_raw.merge(
    df_codici_unita_amministrative[[
        "Codice Comune formato alfanumerico",
        "Ripartizione geografica",
        "Denominazione Regione",
        "Denominazione dell'Unità territoriale sovracomunale \n(valida a fini statistici)"
    ]],
    how="left",
    left_on="Codice Comune",
    right_on="Codice Comune formato alfanumerico",
)

NameError: name 'df_raw' is not defined